---
- hosts: nginx_servers
  gather_facts: false
  become: true

  vars:
    #reactjs_host_ip: {{ ansible_default_ipv4.adress }}
    reactjs_host_ip: 178.154.221.84
    reactjs_host_port: 80
    project_path: /var/www
    repositiry: https://gitlab.com/devops-exr/bluegreen.git
  roles:
    - role: "/home/name/module_08/roles/nginx"

