---
# handlers file for deploy_apache_web

- name: Restart Nginx
  service: name=nginx state=restarted
  when: ansible_os_family == "Debian"

- name: Restart Apache RedHat
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"


